---
name: CI for ansible-role-rss2irc

on: [push]

defaults:
  run:
    working-directory: 'zstyblik.rss2irc'

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the codebase
      uses: actions/checkout@v4
      with:
        path: 'zstyblik.rss2irc'
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-ci.txt
    - name: Run yamllint
      run: |
        ./ci/run-yamllint.sh
    - name: Run ansible-lint
      uses: ansible/ansible-lint@v6.22.2
      with:
        working_directory: 'zstyblik.rss2irc'
